### ISSUE TITLE
Documentation:

### ISSUE THREAD

**Issue by xkianteb** [crgwilson/shipping-and-receiving#1]
Hey,

The initial release seems to be lacking documentation on how to run the package. Do you have an estimate on when you will update the documentation and/or the readme file?

**Comment by crgwilson** [comment]
This repo is still super WIP as I remember how to use the debian build toolbox. The aim of this repo is to build packages to be published to an apt repo and brew formula. Once I get to that stage I'll probably write myself a runbook of sorts.
